package listGenerator.generator;

import linkedList.list.SingleLinkedList;
import linkedList.list.LinkedList;
import linkedList.list.ListAccessError;
import linkedList.node.ListNode;

/**
 * This interface for classes which generate arbitrary list types.
 *
 * This interface specifies the signatures of methods which are to be implemented in separate classes
 *
 * The tester class perform various tests on this interface's properties.
 *
 * @param <T> the type of object in the lists generated by the list generator.
 *
 * @author Ben Scott
 * @version December 2019
 */

public interface ListGenerator<T> {
    /**
     * Generate a random list.
     *
     * @param size the size of the array to be generated.
     * @return a list of the specified size containing elements of the specified type
     *
     * @throws NegativeArraySizeException if the size given is negative.
     * @throws ListAccessError
     */
    public SingleLinkedList<T> getList(int size) throws NegativeArraySizeException, ListAccessError;
}

